apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.nfs.storage | default "100Gi" }}
  volumeName: "{{ .Release.Name }}-minio-nfs-pv"
